### ISSUE TITLE
@font-face support

### ISSUE THREAD

**Issue by ghost** [keithclark/css-feature-toggle-devtools-extension#6]
First off, thanks for this great extension!

I'd find it to be super useful to have support for toggling `@font-face` rules to test fallback fonts in the order of variable fonts → web fonts → system fonts.

Cheers

**Comment by keithclark** [comment]
It should be possible to disable custom fonts with the `atRuleIdentifier` helper that's used to [disable @supports](https://github.com/keithclark/css-feature-toggle-devtools-extension/blob/master/panel/features/supports.js)

My experience with variable fonts is limited. Do you have any thoughts on how to disable them? Is it a case of disabling these rules (or a subset of them)?:

```css
font-style: oblique [value] [...value];
font-variation-settings: [value];
font-optical-sizing: [value];
font-synthesis: [value];
font-stretch: [value];
```

**Comment by indrekpaas** [comment]
I've tried the current `atRuleIdentifier` method, but unfortunately it doesn't work as expected – the fonts don't change when toggle is enabled and will re-render once it's disabled again.

This feature could be trickier than I thought and would require some testing, but after some reading there seems to be two distinct properties to variable fonts:

* The recommended variable font application is done with the `@supports (font-variation-settings: normal) {}` feature query (which the extension already supports), and
* In the `@font-face` rule the `format` can either be `woff2-variations` or `truetype-variations`.

To be honest, I'm not sure how `@font-face` rules would react to live-editing if I had to draw a parallel to `@keyframes` rule (which isn't very approachable in the browser).

[Implementing a variable font with fallback web fonts](https://www.zeichenschatz.net/typografie/implementing-a-variable-font-with-fallback-web-fonts.html) could be a useful reference.

Cheers

**Comment by keithclark** [comment]
I _very_ quickly tested with this and custom fonts toggle as expected for me in Chrome:

```js
import {atRuleIdentifierOption} from '../feature-helpers.js';

export default atRuleIdentifierOption({
  name: 'Custom fonts',
  group: 'Other',
  help: 'Disable support for loading custom fonts',
  identifier: 'font-face'
});
```

Is there a specific URL you're testing against that's failing?

**Comment by keithclark** [comment]
I've done investigation work... 

The extension is behaving as it should. When disabling @font-face support, the style element that sets the font name in CSS Tricks looks like this (note the `-disabled-` prefix on the `@font-face` declaration):

![screen shot 2019-01-16 at 00 03 35](https://user-images.githubusercontent.com/588665/51217994-5d839e00-1922-11e9-8b7b-fccfea2b6b4a.png)

... and when you re-enable support, the same block looks like this:

![screen shot 2019-01-16 at 00 03 19](https://user-images.githubusercontent.com/588665/51218013-755b2200-1922-11e9-8405-d4b0a874e523.png)

If you use the *Elements* tab to rename that font to `Rubik2`, Chrome will continue to use the old name *and* the new one. Therefore, anything using `font-family: Rubik` will still be rendered with a custom font, which I believe is a bug.

Also, if you remove that entire `<style>` block, the font is still applied. Again, I think that's a bug.

My hunch is this is caused by `<link rel="preload">` but more investigation is required:

```html
<link rel="preload" href="https://css-tricks.com/wp-content/themes/CSS-Tricks-17/fonts/Rubik-Bold-kern-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="https://css-tricks.com/wp-content/themes/CSS-Tricks-17/fonts/Rubik-Regular-kern-latin.woff2" as="font" type="font/woff2" crossorigin>
```

**Comment by keithclark** [comment]
After digging deeper into this and talking to others it looks like css-tricks is using JavaScript to load the fonts using the [Font Loading API](https://www.w3.org/TR/css-font-loading-3/), which is why they continue to render despite removing all font related CSS rules.

It looks like the workaround for this is to use `document.fonts.clear()`, which should clear out everything. Working out when to call that method is the next piece in the puzzle.

This looks like an edge case so, in the short term, I'm tempted to create a PR based on https://github.com/keithclark/css-feature-toggle-devtools-extension/issues/6#issuecomment-454378761 so `@font-face` toggling is possible in the majority of cases.

**Comment by keithclark** [comment]
#13 should covers the first part of this issue.
